#ifndef ACATA_H
#define ACATA_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>

#include "shared/speed/ata.h"
#include "shared/ata/isif.h"
#include "shared/ata/raw.h"

#include "iop/intc.h"

#define ACATA_R_DATA                0x16000000  // Read/Write PIO data bytes
#define ACATA_R_FEATURE             0x16010000  // [W] Used to control command specific interface features.
#define ACATA_R_ERROR          ACATA_R_FEATURE  // [R] Used to retrieve any error generated by the last ATA command executed.    
#define ACATA_R_NSECTOR             0x16020000  // Number of sectors to read/write (0 is a special value).
#define ACATA_R_SECTOR              0x16030000  // This is CHS / LBA28 / LBA48 specific.
#define ACATA_R_LCYL                0x16040000  // Partial Disk Sector address.
#define ACATA_R_HCYL                0x16050000  // Partial Disk Sector address.
#define ACATA_R_SELECT              0x16060000  // Used to select a drive and/or head. Supports extra address/flag bits. 0x10 bit determines drive
#define ACATA_R_STATUS              0x16070000  // [R] Used to read the current status.
#define ACATA_R_COMMAND         ACATA_R_STATUS  // [W] Used to send ATA commands to the device.
#define ACATA_R_STATUS_ALT          0x16160000  // [R] A duplicate of the Status Register which does not affect interrupts.
#define ACATA_R_CONTROL     ACATA_R_STATUS_ALT  // [W] Used to reset the bus or enable/disable interrupts.

struct s2x6_acata {
    struct ata_hdd hdd;

    uint16_t data;
    uint16_t error;
    uint16_t feature;
    uint16_t nsector;
    uint16_t sector;
    uint16_t lcyl;
    uint16_t hcyl;
    uint16_t select;
    uint16_t status;
    uint16_t command;
    uint16_t control;

    uint8_t* buf;
    uint32_t buf_index;
    uint32_t buf_size;

    uint64_t pending_sectors;
    uint64_t pending_lba;

    uint8_t identify[ATA_SECTOR_SIZE];

    struct ps2_iop_intc* intc;
    struct sched_state* sched;
};

struct s2x6_acata* s2x6_acata_create(void);
void s2x6_acata_init(struct s2x6_acata* acata, struct ps2_iop_intc* intc, struct sched_state* sched);
int s2x6_acata_load(struct s2x6_acata* acata, const char* path);
void s2x6_acata_destroy(struct s2x6_acata* acata);
uint64_t s2x6_acata_read16(struct s2x6_acata* acata, uint32_t addr);
void s2x6_acata_write16(struct s2x6_acata* acata, uint32_t addr, uint64_t data);

#ifdef __cplusplus
}
#endif

#endif