name: macOS CI

on:
  push:
  pull_request:

jobs:
  macos-universal-build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v6
      with:
        submodules: 'recursive'
        fetch-depth: 0

    - name: Apply dependency patches
      run: git -C deps/parallel-gs/Granite apply "${{ github.workspace }}/deps/patches/granite-arm64-simd-headers.patch"

    - name: Install Vulkan SDK
      uses: jakoch/install-vulkan-sdk-action@v1
      with:
        optional_components: com.lunarg.vulkan.volk
        install_runtime: true
        cache: true
        stripdown: true

    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install mbedTLS codegen deps
      run: pip install -r deps/mbedtls/scripts/basic.requirements.txt

    - name: Build and pack Iris
      run: |
        git fetch --all --tags
        cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=Release
        cmake --build build
        sudo cmake --install build
        mkdir -p ./build/dist
        cp -R ./build/iris.app ./build/dist

    - uses: actions/upload-artifact@v7
      with:
        name: iris-latest-macos-universal
        path: ./build/dist
