name: Windows CI

on:
  push:
  pull_request:

jobs:
  build:
    name: ${{ matrix.arch }}
    runs-on: ${{ matrix.runner }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: amd64
            runner: windows-2025-vs2026
          - arch: arm64
            runner: windows-11-arm

    steps:
    - uses: actions/checkout@v6
      with:
        submodules: 'recursive'
        fetch-depth: 0

    - name: Configure build for ${{ matrix.arch }}
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: ${{ matrix.arch }}

    - name: Build and pack Iris
      run: |
        git fetch --all --tags
        cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=clang-cl -DCMAKE_CXX_COMPILER=clang-cl
        cmake --build build
        New-Item -Path "dist" -ItemType Directory
        Copy-Item -Path ".\build\iris.exe" "dist"

    - uses: actions/upload-artifact@v7
      with:
        name: iris-latest-windows-${{ matrix.arch }}
        path: dist/
